import React, { useContext, useState } from 'react';
import {UserContext} from '@/context/UserContext';
import Head from 'next/head';
import Link from 'next/link';
import PrimaryBtn from '@/components/PrimaryBtn';

const LoginPage = () => {

  const { handleLogIn } = useContext(UserContext);
  const [name, setName] = useState<string>("");
  const [surname, setSurname] = useState<string>("");
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [address, setAddress] = useState<string>("");
  const [phone, setPhone] = useState<string>("");
  const [biography, setBiography] = useState<string>("");


  return (
    <>
      <Head>
        <title>Igralishte - Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className="d-flex flex-column justify-content-center"
          onSubmit={(event: React.FormEvent<HTMLFormElement>) => {
          event.preventDefault();
          handleLogIn(username, password);
          }}>

          <div className='container-fluid mt-5 text-center'>
            <div className='row d-flex flex-column justify-content-center'>
              <div className='col-12 mt-5'>
                <Link href={"/"}><img src="../pictures/icons/Logo Igralishte final version.png" alt="logo-igralishte" /></Link>
                <div className='col-12 mt-5 mb-3 text-center'>
                  <img src="../pictures/Profile-picture.png" alt="profile picture" />
                  </div>
                  <div className='col-12 mb-3 text-center'>
                  <button className='btnProfilePicture small p-0 px-2 border-0'>Одбери слика</button>
                </div>
              </div>
              {/* <div className='row d-flex flex-row justify-content-left'> */}
              <div className='mb-3 col-12 px-4 text-left'>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="name">Име</label>
                <input type="text" id="name" className="PrimaryBtn w-100" style={{fontWeight: "lighter"}} placeholder="Ивана" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setName(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="surname">Презиме</label>
                <input type="text" id="surname" className="PrimaryBtn w-100" style={{fontWeight: "lighter"}} placeholder="Голабоска" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setSurname(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="username">Email адреса</label>
                <input type="email" id="username" className="PrimaryBtn w-100" style={{fontWeight: "lighter"}} placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                  setUsername(event.target.value);
                  }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
              <label htmlFor="password">Лозинка</label>
              <input type="password" id="password" className="PrimaryBtn w-100" style={{fontWeight: "lighter"}} placeholder="********" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                  setPassword(event.target.value);
                  }} /> 
              </div>
              <div className='d-flex flex-column justify-content-left'>
              <Link href="/profile/password"><p style={{color: "#8A8328", textDecoration: "underline"}}>Промени лозинката</p></Link>
                <label htmlFor="address">Адреса</label>
                <input type="text" id="address" className="PrimaryBtn w-100" style={{fontWeight: "lighter"}} placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setAddress(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="phone">Телефонски број</label>
                <input type="text" id="phone" className="PrimaryBtn w-100" style={{fontWeight: "lighter"}} placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setPhone(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="biography">Биографија</label>
                <input type="textarea" id="biography" className="PrimaryBtn w-100" style={{fontWeight: "lighter", height: "80px" }} placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setBiography(event.target.value);
                    }}/>
              </div>
                <div className="input-group my-3">
                  <div className="input-group-prepend">
                    <div className="input-group-text border-0 bg-transparent px-1">
                      <input type="checkbox" aria-label="Checkbox for following text input"/>
                    </div>
                  </div>
                  <input type='text' style={{fontSize: "10px", fontFamily: "Inter"}} className="form-control border-0" aria-label="Text input with checkbox" placeholder='Испраќај ми известувања за нови зделки и промоции.'/>
                </div>
              <PrimaryBtn title="Зачувај" btnClass={"PrimaryBtn"} backgroundColor={"black"} color='white' border='none'/>
                </div>
              </div>
            </div>
        </form>
      </>
    );

}

export default LoginPage