import React, { useState } from 'react'
import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import ProductItem from '@/components/ProductItem';
import { ProductType } from '@/types/types';
import { useRouter } from 'next/router';
import Pagination from '@/components/Pagination';
import Link from 'next/link';
import PrimaryBtn from '@/components/PrimaryBtn';



interface Props {
  products: ProductType[];
  searchedProductsData: ProductType[];
}

const ProductPage: NextPage<Props> = ({  products, searchedProductsData }) => {
    
    
    const router = useRouter();
    const [toggleSearch, setToggleSearch] = useState(false);

  const [searchState, setSearchState] = useState("");

//   const handleSearchSubmit = (event: React.FormEvent) => {
//       event.preventDefault();
//       router.push({
//         pathname: "/products",
//         query: { query: searchState },
//         });
//       setSearchState("");
//   }

  const handleToggleSearch = () => {
    setToggleSearch(!toggleSearch);
  }

   

  return (
    < >

      <Head>
        <title>Igralishte - Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='col-12 p-0 search-navbar'>
            <button onClick={handleToggleSearch} className='bg-transparent border-0 ml-4'>
                <img src="../../pictures/icons/search-group.png"/>
            </button>
            <div className={`${toggleSearch ? "activeSearch" : "search"} flex-column justify-content-start text-left`}>
            <div className="col-11 p-0 my-5 mr-auto ml-auto">
            <div className="col-11">
            <div className="wrap-search-header flex-w p-l-15 align-items-center">
                <div className="col-12 p-0 m-0 text-center mr-auto ml-auto">
                    <input
                        className="w-100 pl-3"
                        style={{height: '34px'}}
                        type="search"
                        name="search-product"
                        placeholder="Пребарувај ..."
                        onChange={(event) => {
                        event.preventDefault();
                        router.push({
                        pathname: "/products",
                        query: {
                            ...router.query,
                            query: event.target.value,
                            },
                        });
                    }}
                        />
                    <img src="../pictures/icons/search.png" className="btn-search btn-search-products" alt="search close btn" onClick={handleToggleSearch}/>
                    </div>
                </div>
                <ul>
                    <li  className="flex-column justify-content-start">
                    <p className="menu-list w-100 mt-5">
                        Категорија
                    </p>
                    <hr className='ml-0 mb-2 mt-3 w-50' style={{paddingBottom: '0.5px', background: "linear-gradient(99.4deg, #FFF0BF -10.68%, #EFC990 100%, #FDD292 100%, rgba(240, 199, 73, 0.42) 81.17%, #D4AF37 100%)"}}/>
                    <div className="d-flex flex-column mr-auto ">
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "tops",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Блузи</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "pants",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Панталони</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "bottomsShorts",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Здолништа / шорцеви</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "dresses",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Фустани</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "coatsAndJackets",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Палта и јакни</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "underwear",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Долна облека</p>
                        </div>                        
                    </div>
                    </li>
                    <li  className="flex-column justify-content-start">
                    <p className="menu-list w-100 my-5">
                        Брендови
                    </p>
                    <hr className='ml-0 mb-2 mt-3 w-50' style={{paddingBottom: '0.5px', background: "linear-gradient(99.4deg, #FFF0BF -10.68%, #EFC990 100%, #FDD292 100%, rgba(240, 199, 73, 0.42) 81.17%, #D4AF37 100%)"}}/>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "pincPartywear",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Pinc Partywear</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "factoryGirl",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Factory Girl</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "mainDays",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Main Days</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "nezno",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Нежно</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "red",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Ред</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "nas",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Наш</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "zsDaNe",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Зш да не</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "fraeil",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Fraeil</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "urma",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Urma</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "candleNest",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Candle Nest</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "beyondGreen",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Beyond Green</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/brands",
                                        query: {
                                            ...router.query,
                                            brand: "gatta",
                                            },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Gatta</p>
                        </div>
                    </li>
                    <li  className="flex-column justify-content-start">
                    <p className="menu-list w-100 my-5">
                        Аксесоари
                    </p>
                    <hr className='ml-0 mb-2 mt-3 w-50' style={{paddingBottom: '0.5px', background: "linear-gradient(99.4deg, #FFF0BF -10.68%, #EFC990 100%, #FDD292 100%, rgba(240, 199, 73, 0.42) 81.17%, #D4AF37 100%)"}}/>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "purses",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Ташни</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            subcategory: "jewelry",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Накит</p>
                        </div>
                    </li>
                    <li  className="flex-column justify-content-start">
                    <p className="menu-list w-100 my-5">
                        Величина
                    </p>
                    <hr className='ml-0 mb-2 mt-3 w-50' style={{paddingBottom: '0.5px', background: "linear-gradient(99.4deg, #FFF0BF -10.68%, #EFC990 100%, #FDD292 100%, rgba(240, 199, 73, 0.42) 81.17%, #D4AF37 100%)"}}/>
                    <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            size: "XL",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >XL</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            size: "L",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >L</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            size: "M",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >M</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            size: "S",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >S</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            size: "XS",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >XS</p>
                        </div>
                    </li>
                    <li  className="flex-column justify-content-start">
                    <p className="menu-list w-100 my-5">
                        Боја
                    </p>
                    <hr className='ml-0 mb-2 mt-3 w-25' style={{paddingBottom: '0.5px', background: "linear-gradient(99.4deg, #FFF0BF 0%, #EFC990 100%, #FDD292 100%)"}}/>
                    <div className="flex-row justify-content-start mt-3 mb-1">
                        <div className="input-group-text">
                            <input type="color" value="#ff0000" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "red",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        <div className="input-group-text">
                            <input type="color" value="#ffa500" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "orange",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        <div className="input-group-text">
                            <input type="color" value="#ffff00" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "yellow",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        <div className="input-group-text">
                            <input type="color" value="#008000" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "green",
                                        },
                                    });
                                }} />
                        </div>
                        <div className="input-group-text">
                            <input type="color" value="#0000ff" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "blue",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                    </div>
                    <div className="flex-row justify-content-start">                       
                        <div className="input-group-text">
                            <input type="color" value="#ffc0cb" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "pink",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        <div className="input-group-text">
                            <input type="color" value="#ee82ee" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "purple",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        <div className="input-group-text">
                            <input type="color" value="#808080" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "grey",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        <div className="input-group-text" >
                            <input type="color" value="#ffffff" aria-label="Checkbox for following text input" className="color-filter mr-2 border"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "white",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        <div className="input-group-text">
                            <input type="color" value="#000000" aria-label="Checkbox for following text input" className="color-filter mr-2"
                                onClick={(event: React.MouseEvent<HTMLElement>) => {
                                    event.preventDefault()
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            color: "black",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                        </div>
                        </div>
                    </li>
                    <li  className="flex-column justify-content-start">
                    <p className="menu-list w-100 my-5">
                        Цена
                    </p>
                    <hr className='ml-0 mb-2 mt-3 w-25' style={{paddingBottom: '0.5px', background: "linear-gradient(99.4deg, #FFF0BF -10.68%, #EFC990 100%, #FDD292 100%, rgba(240, 199, 73, 0.42) 81.17%, #D4AF37 100%)"}}/>
                    <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            discount: "discount",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >На попуст*</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            price: "price",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >500 - 1000 ден.</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            price: "price",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >1500 - 2000 ден.</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            price: "price",
                                        },
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >2000 - 2500 ден.</p>
                        </div>
                        <div className="input-group-text">
                            <input type="checkbox" aria-label="Checkbox for following text input"
                                onClick={() => {
                                    router.push({
                                        pathname: "/products",
                                        query: {
                                            ...router.query,
                                            price: "price",
                                        }
                                    });
                                    {handleToggleSearch};
                                }} />
                            <p className="p-0 ml-3" >Над 2500 ден.</p>
                        </div>
                    </li>
                   </ul>
                </div>
                    {/* <div className='row flex-column justify-content-center bottom-sticky'> */}
                    <div className='col-11 p-0 text-center mb-4 mr-auto ml-auto bottom-sticky'>
                        <PrimaryBtn title="Филтрирај" btnClass={"PrimaryBtn w-100 btn-gold btn-gold-text mb-3"} onClick={handleToggleSearch} backgroundColor={"btn-gold"} color='black' border='none' height="51px"/>
                        <button className='border-0 bg-transparent w-100' onClick={handleToggleSearch}><u>oткажи</u></button>
                    </div>
                </div>
                </div>
        </div>
        {/* SEARCH LAYER END */}
        <div className="container my-5">
          <div  className="row flex-column">
            <div className="container">
              <div  className="row flex-row">
                <div className="col-12 flex-row flex-wrap justify-content-around">
                  {searchedProductsData.length > 0 ? (
                    searchedProductsData?.map((product, productIndex) => {
                    let columnSize = "col-5 product-img-small";
                    let columnText = "product-text-a"
                    for (let i = 2; i < searchedProductsData.length; i += 5) {
                    if (productIndex === i ) {columnSize = "col-11"; columnText = "product-text"}}
                        return (
                            <div key={productIndex} className={`${columnSize} ${columnText} p-0 mb-2`}>
                            <ProductItem   id={product.id} title={product.title} img={product.img} price={product.price}/>
                            </div>
                        );
                    })
                    ) : (
                        <div>No products found.</div>
                    )}

                </div>
              </div>
            </div>
          </div>
        </div>
        {/* pagination  */}
        <Pagination products={searchedProductsData}/>

    </>
  ); 
};

export default ProductPage;



 export const getServerSideProps: GetServerSideProps = async ({query}) => { 
     
     const page = parseInt(query.page as string, 10) || 1;
     
     const response = await fetch(`http://localhost:5001/products?_page=${page}`); 
     const products: ProductType[] = await response.json();

    
    let resSearchedProducts: Response;

    // if (query.category && query.subcategory) {
    //     resSearchedProducts = await fetch(
    //     `http://localhost:5001/products?category_like=${query.category}&q=${query.subcategory}`
    //     );
    // } 
    if (query.brand) {
        resSearchedProducts = await fetch(
            `http://localhost:5001/products?brand_like=${query.brand}`
            );
    } 
    else if (query.subcategory) {
        resSearchedProducts = await fetch(
        `http://localhost:5001/products?subcategory_like=${query.subcategory}`
        );
    } 
    else if (query.size) {
        resSearchedProducts = await fetch(
        `http://localhost:5001/products?size_like=${query.size}`
        );
    }
    else if (query.color) {
        resSearchedProducts = await fetch(
        `http://localhost:5001/products?color_like=${query.color}`
        );
    } 
    else if (query.price) {
        resSearchedProducts = await fetch(
        `http://localhost:5001/products?price_like=${query.price}`
        );
    }   
    else {
        resSearchedProducts = await fetch(`http://localhost:5001/products?_page=${page}`);
    }

    const searchedProductsData: ProductType[] = await resSearchedProducts.json();

return { 
    props: { 
        products, 
        page,
        searchedProductsData
    },
    }
 }