import PageTitle from '@/components/PageTitle';
import { CategoryType, DataType, ProductType, SubcategoryType } from '@/types/types';
import { GetServerSideProps, GetStaticPaths, GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react'



interface Props {
  product: ProductType;
  // randomProducts: ProductType[];
  allproducts: ProductType[]
}

const ProductDetailPage: NextPage<Props> = ({ product, allproducts }) => {


//   const router = useRouter();
// const { id } = router.query;

// if (router.isFallback) {
// return <div>Loading...</div>;
// }


return (
    <>
      <Head>
        <title>{product.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={product.title} />

        <div className="container-fluid my-5">
          <div className="row d-flex flex-column justify-content-center">
            <div className="col-12 h-100">
              {allproducts?.map((item) => {
                if (product.id === item.id) {
                  return (
                      < div key={item.id}>
                      <img src={item.img} alt="IMG-PRODUCT" />
                      </div>
                      )
                    }
              })}
            </div>
            <div className="col-12">
                <h4 className="text-center">{product.title}</h4>
                <span className="text-center">{product.price}</span>
                <p className="text-left">{product.description}</p>
          </div>
            <div className="col-12">
              <img src="../../pictures/about-banner1.png" alt="probna slikicka" />
              {product.id}
              </div>


          {/* <RelatedProducts products={randomProducts}/> */}
        </div>
      </div>
    </>
  );
};


export default ProductDetailPage;



export const getStaticPaths: GetStaticPaths = async () => {

  const resClothes = await fetch('http://localhost:5001/vintageClothes');
  const vintageClothes: SubcategoryType[] = await resClothes.json();
  // const res = await fetch("http://localhost:5001/vintageClothes");
  // const data: DataType = await res.json();

  const allproducts = vintageClothes?.flatMap((category) => {
    return Object.values(category).flatMap((productList: ProductType[]) => productList);
  });

  const paths = allproducts?.map((product: ProductType) => ({
    params: {
      id: String(product.id),
    },
  }));

  return {
    paths,
    fallback: false,
  };
};


//   let allproducts: ProductType[] = []


//   const pathsArray = vintageClothes.forEach((category: SubcategoryType) => {
//         Object.values(category).forEach((productList: ProductType[]) => {
//             productList.forEach((product: ProductType) => {
//                 allproducts?.push(product);
            
//             });
//         });
//     });

//   const paths = allproducts.map((item) => {
//           return (
//                 {id: item.id.toString()}
//               )
//             }
//       )

//   return {
//     paths,
//     fallback: false,
//   };
// }


export const getStaticProps: GetStaticProps = async ({ params }) => {

  let product: ProductType | undefined = undefined;

  const resProductsCount = await fetch("http://localhost:5001/vintageClothes");
  const vintageClothes: SubcategoryType[] = await resProductsCount.json();

  // let allproducts: ProductType[] = vintageClothes.flatMap((category: SubcategoryType) => {
  //   return Object.values(category).flatMap((productList: ProductType[]) => productList);
  // });

  // let randomProducts: ProductType[] = [];

  // if (allproducts.length > 4) {
  //   const randomNo = Math.floor(Math.random() * (allproducts.length - 4));
  //   const resRandomProducts = await fetch(`http://localhost:5001/products?_start=${randomNo}&_limit=4`);
  //   randomProducts = await resRandomProducts.json();
  // }


  let allproducts: ProductType[] = []


    vintageClothes.forEach((category: SubcategoryType) => {
        Object.values(category).forEach((productList: ProductType[]) => {
            productList.forEach((product: ProductType) => {
            if (allproducts.length <= 10 && product.id) {
                allproducts?.push(product);
            } else {
                return;
            }
            });
        });
    });

  console.log(params?.id)

  if (params?.id) {
    const resProduct = await fetch(`http://localhost:5001/vintageClothes/${params.id}`);
    product = await resProduct.json();
  }

  console.log(product)
  return {
    props: {
      product,
      // randomProducts,
      allproducts,
    },
  };
};