import PageTitle from "@/components/PageTitle";
import PrimaryBtn from "@/components/PrimaryBtn";
import { UserContext } from "@/context/UserContext";
import { ContactType, FAQType } from "@/types/types";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import React, { useContext } from "react";


interface Props {
  faqData: FAQType[];
}


const Contact: NextPage<Props> = ({ faqData }) => {



return (
    <>
      <Head>
        <title>Igralishte - FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="d-flex flex-row align-items-center align-self-center my-3 justify-content-center">
        <PageTitle title="FAQ"/>
        <img src="../pictures/icons/sparks-elements.png" alt="spakrs" className="ml-2"/>
      </div>

      <div className="container mb-5">
          <div className="row d-flex flex-column justify-content-center mr-auto ml-auto">
            <div className="col-11 faq-container mr-auto ml-auto p-0">
            {faqData.map((question) => {
              return (
                <div className="about-text faq-item" key={question.id}>
                  <div className="d-flex flex-row justify-content-start faq-item-olive">
                    <p className="mr-2">{question.id}.</p>
                    <p>{question.question}</p>
                  </div>
                  <p className="p-0">{question.answer}</p>
                  <hr className="hr-line-faq"/>
                </div>
              )
            })}
          </div>
        </div>
      </div>
    </>
  );
};

export default Contact;

export const getStaticProps: GetStaticProps = async () => {

  const res = await fetch("http://localhost:5001/FAQ");
  const faqData: FAQType[] = await res.json();

  return {
    props: {
      faqData,
    },
  };

};
