import Head from 'next/head'
import { Inter } from 'next/font/google'
import { NextPage } from 'next'

const inter = Inter({ subsets: ['latin'] })

// interface Props {
//   bannerData: BannerType,
//   featuredProductData: ProductType[],
//   featuredBlogsData: BlogType[],
// }

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ИГРАЛИШТЕ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
{/*         
      <Banner preTitle={bannerData.preTitle} title={bannerData.title}/>

      <CategoryPicker />

      <FeaturedProducts products={featuredProductData}/>

      <FeaturedBlogs blogs={featuredBlogsData}/> */}
        
      </main>
    </>
  )
}

export default Home;


// export const getStaticProps: GetStaticProps = async () => {

//  const resBanner = await fetch("http://localhost:5001/banner_content");
//  const bannerData: BannerType= await resBanner.json();

//  const resFeaturedProduct = await fetch("http://localhost:5001/products/?_limit=4");
//  const featuredProductData: ProductType[] = await resFeaturedProduct.json();

//  const resFeaturedBlogs = await fetch("http://localhost:5001/blogs/?_limit=3");
//  const featuredBlogsData: BlogType[] = await resFeaturedBlogs.json();

//  return {
//     props: {
//       bannerData,
//       featuredProductData,
//       featuredBlogsData,
//     },
//  };
// };