import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import LoginForm from '@/components/LoginForm';

const LoginPage = () => {
   
  return (
    <>
      <Head>
        <title>Igralishte - Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container-fluid mt-5'>
        <div className='row d-flex flex-column justify-content-center'>
          <div className='col-12 mt-5 mb-4 text-center'>
            <Link href={"/"}><img src="../pictures/icons/Logo Igralishte final version.png" alt="logo-igralishte" /></Link>
          </div>
          <div className='col-10 mr-auto ml-auto mt-5'>
            <LoginForm />
          </div>
        </div>
      </div>
    </>
  );
}

export default LoginPage