import Head from 'next/head';
import LoginForm from '../components/LoginForm'
import React from 'react'
import PageTitle from '@/components/PageTitle';

const LoginPage = () => {
   
  return (
    <>
      <Head>
        <title>Store - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={"About"}/>
      <div className='container'>
        <img src="../pictures/icons/Logo Igralishte final version 1.png" alt="logo-igralishte" />   
        <LoginForm />
      </div>
    </>
  );
}

export default LoginPage