import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import RegisterForm2 from "@/components/RegisterForm2";
import RegisterForm3 from "@/components/RegisterForm3";
import PrimaryBtn from "@/components/PrimaryBtn";
import Link from "next/link";


type ActiveView = "register" | "register2" | "register3";

const RegisterPage: NextPage = () => {

  const [view, setView] = useState<ActiveView>("register");

   function handleView(newView: ActiveView) {
    setView(newView);
 }

  console.log(view)

  return (
    <>
      <Head>
        <title>Igralishte - Register Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
          <div className="row d-flex flex-column justify-content-center mr-auto ml-auto">
            <div className="col-12">
          <form className="d-flex flex-column justify-content-center">
          <div className='text-center mb-5'>
            <PrimaryBtn btnClass={"SecondaryBtn w-100"}  onClick={() => handleView("register2")} title="Регистрирај се со емаил адреса" backgroundColor={"transparent"} color='black' height="40px" border='3px solid #FFDBDB'/>            
            <p className='text-center my-4'>или</p>
            <PrimaryBtn btnClass={"SecondaryBtn w-100"} img="../pictures/icons/google.png" title="Најави се преку Google" backgroundColor={"transparent"} color='black' height="40px" border='3px solid #FFDBDB'/>
            <PrimaryBtn btnClass={"SecondaryBtn w-100"}  img="../pictures/icons/facebook.png" title="Најави се преку Facebook" backgroundColor={"transparent"} color='black' height="40px" border='3px solid #FFDBDB'/>
            <Link href="/login"><p className='mr-2 mt-4 mb-5 text-dark font-weight-bold'>Веќе имаш профил? <span style={{color: "#8A8328", textDecoration: "underline"}}> Логирај се</span></p></Link>
          </div>

          <p className='note'>Сите права задржани @ Игралиште Скопје</p>
      </form>
              <div className="container p-0 mr-auto ml-auto">
                {/* {view === "register" ? <RegisterForm1 /> : null} */}
                {view === "register2" ? <RegisterForm2 /> : null}
                {view === "register3" ? <RegisterForm3 /> : null}

              </div>
            </div>
          </div>
        </div>
    </>
  );
};

export default RegisterPage;

