import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useContext, useState } from "react";
import PrimaryBtn from "@/components/PrimaryBtn";
import Link from "next/link";
import { UserContext } from "@/context/UserContext";


type ActiveView = "register" | "register-2" | "register-3";


const RegisterPage: NextPage = () => {


  const { handleLogIn } = useContext(UserContext);

  const [view, setView] = useState<ActiveView>("register");
  const [name, setName] = useState<string>("");
  const [surname, setSurname] = useState<string>("");
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [address, setAddress] = useState<string>("");
  const [phone, setPhone] = useState<string>("");
  const [biography, setBiography] = useState<string>("");


  const handleChangeView1 = () => {
    setView(view === 'register' ? 'register-2' : 'register');
  };

  const handleChangeView2 = () => {
    setView(view === 'register-2' ? 'register-3' : 'register');
  };

  useEffect(() => {
    console.log('View changed to:', view);
 }, [view]);


  return (
    <>
      <Head>
        <title>Igralishte - Register Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {view === "register" ? 

      <div className="container my-5">
          <div className="row d-flex flex-column justify-content-center mr-auto ml-auto">
            <div className="col-12">
            <form className="d-flex flex-column justify-content-center">
            <div className='text-center mb-5'>
              <PrimaryBtn btnClass={"SecondaryBtn w-100"}  onClick={handleChangeView1} title="Регистрирај се со емаил адреса" backgroundColor={"transparent"} color='black' height="40px" border='3px solid #FFDBDB'/>            
              <p className='text-center my-4'>или</p>
              <PrimaryBtn btnClass={"SecondaryBtn w-100"} img="../pictures/icons/google.png" title="Најави се преку Google" backgroundColor={"transparent"} color='black' height="40px" border='3px solid #FFDBDB'/>
              <PrimaryBtn btnClass={"SecondaryBtn w-100"}  img="../pictures/icons/facebook.png" title="Најави се преку Facebook" backgroundColor={"transparent"} color='black' height="40px" border='3px solid #FFDBDB'/>
              <Link href="/login"><p className='mr-2 mt-4 mb-5 text-dark font-weight-bold'>Веќе имаш профил? <span style={{color: "#8A8328", textDecoration: "underline"}}> Логирај се</span></p></Link>
              </div>
              <p className='note'>Сите права задржани @ Игралиште Скопје</p>
            </form>
        </div>
        </div>
      </div>
       : null }

      {view === "register-2" ? 

      <div className="container p-0 my-5 mr-auto ml-auto">
        <form className="d-flex flex-column justify-content-center"
          onSubmit={(event: React.FormEvent<HTMLFormElement>) => {
          handleLogIn(username, password);
          }}>

          <div className='container-fluid mt-5 text-center'>
            <div className='row d-flex flex-column justify-content-center'>
              <div className='col-12 mt-5'>
                <Link href={"/"}><img src="../pictures/icons/Logo Igralishte final version.png" alt="logo-igralishte" /></Link>
                <div className='col-12 mt-5 mb-3 text-center'>
                  <img src="../pictures/Profile-picture.png" alt="profile picture" />
                  </div>
                  <div className='col-12 mb-3 text-center'>
                  <button className='btnProfilePicture small p-0 px-2 border-0'>Одбери слика</button>
                </div>
              </div>
              <div className='mb-3 col-11 px-4 text-left mr-auto ml-auto'>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="name">Име</label>
                <input type="text" id="name" className="PrimaryBtn form-input" placeholder="Ивана" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setName(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="surname">Презиме</label>
                <input type="text" id="surname" className="PrimaryBtn form-input" placeholder="Голабоска" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setSurname(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="username">Email адреса</label>
                <input type="email" id="username" className="PrimaryBtn form-input" placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                  setUsername(event.target.value);
                  }}/>
              </div>
               <div className='d-flex flex-column justify-content-left'>
              <label htmlFor="password">Лозинка</label>
              <input type="password" id="password" className="PrimaryBtn form-input" placeholder="********" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                  setPassword(event.target.value);
                  }} /> 
              </div>
              <div className='d-flex flex-column justify-content-left'>
              <label htmlFor="conf-password">Повтори лозинка</label>
              <input type="password" id="conf-password" className="PrimaryBtn form-input" placeholder="********" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                  setPassword(event.target.value);
                  }} /> 
              </div>
              
              
              <PrimaryBtn onClick={handleChangeView2}  title="Регистрирај се"  btnClass={"PrimaryBtn w-75"} backgroundColor={"black"} color='white' height={"40px"} border='none'/>
              
              <p className='note'>Со вашата регистрација, се согласувате со Правилата и Условите за кориснички сајтови.</p>
              </div>
            </div>
          </div>
        </form>
        </div>
      : null}

        {view === "register-3" ? 

        <form className="d-flex flex-column justify-content-center"
          onSubmit={(event: React.FormEvent<HTMLFormElement>) => {
          handleLogIn(username, password);
          }}>

          <div className='container-fluid mt-5 text-center'>
            <div className='row d-flex flex-column justify-content-center'>
              <div className='col-12 mt-5'>
                <Link href={"/"}><img src="../pictures/icons/Logo Igralishte final version.png" alt="logo-igralishte" /></Link>
                <div className='col-12 mt-5 mb-3 text-center'>
                  <img src="../pictures/Profile-picture.png" alt="profile picture" />
                  </div>
                  <div className='col-12 mb-3 text-center'>
                  <button className='btnProfilePicture small p-0 px-2 border-0'>Одбери слика</button>
                </div>
              </div>
              <div className='mb-3 col-11 px-4 text-left mr-auto ml-auto'>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="address">Адреса</label>
                <input type="text" id="address" className="PrimaryBtn form-input" placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setAddress(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="phone">Телефонски број</label>
                <input type="text" id="phone" className="PrimaryBtn form-input" placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setPhone(event.target.value);
                    }}/>
              </div>
              <div className='d-flex flex-column justify-content-left'>
                <label htmlFor="biography">Биографија</label>
                <input type="textarea" id="biography" className="PrimaryBtn w-100 p-3 text-left" style={{fontWeight: "lighter", height: "80px" }} placeholder="example@example.com" onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setBiography(event.target.value);
                    }}/>
              </div>
                <div className="input-group my-3">
                  <div className="input-group-prepend">
                    <div className="input-group-text border-0 bg-transparent px-1">
                      <input type="checkbox" aria-label="Checkbox for following text input"/>
                    </div>
                  </div>
                  <input type='text' style={{fontSize: "10px", fontFamily: "Inter"}} className="form-control border-0" aria-label="Text input with checkbox" placeholder='Испраќај ми известувања за нови зделки и промоции.'/>
                </div>
              <Link href="/"><PrimaryBtn title="Заврши" onClick={() => {handleLogIn}} btnClass={"PrimaryBtn w-75"} backgroundColor={"black"} color='white' height={"40px"} border='none'/></Link>
              
              <Link href="/login"><p style={{color: "black", textDecoration: "underline"}}>Прескокни</p></Link>
              </div>
              </div>
            </div>
        </form>

        : null}

         
    </>
  );
};

export default RegisterPage;

