import React, { useContext, useEffect, useRef, useState } from 'react'
import Head from 'next/head';
import { useRouter } from 'next/router';
import { UserContext } from '@/context/UserContext';
import { GetStaticPaths, GetStaticProps, NextPage } from 'next';
import BoxComponent from '@/components/BoxComponent';
import PageTitle from '@/components/PageTitle';
import RelatedProducts from '@/components/RelatedProducts';
import { BoxComponentType, DataType, ProductType } from '@/types/types';


interface Props {
  product: ProductType;
  products: DataType["products"];
  allProducts: ProductType[];
  randomProducts: ProductType[];
  boxItemsData: BoxComponentType[];
}

const OrderPage: NextPage<Props> = ({ product, products, allProducts, boxItemsData, randomProducts }) => {


  const { useFetchAllProducts, addToCard} = useContext(UserContext);


  const router = useRouter();

  const [expandedBox, setExpandedBox] = useState(null);
   
  const [page, setPage] = useState(1);
  const totalPages = 10;
  const [itemProducts, setItemProducts] = useState(allProducts.slice(0, 10));
  const [currentIndex, setCurrentIndex] = useState(0);
  const [activePage, setActivePage] = useState(1);
    
const handlePrevClick = () => {
        setPage(page - 1);
        setActivePage(page - 1);
        if (currentIndex > 0) {
        setCurrentIndex(currentIndex - 10);
        setItemProducts(allProducts.slice(currentIndex - 10, currentIndex));
        }
  };

  const handleNextClick = () => {
    setPage(page + 1);
        setActivePage(page + 1);
        if (currentIndex + 10 < allProducts.length) {
        setCurrentIndex(currentIndex + 10);
        setItemProducts(allProducts.slice(currentIndex + 10, currentIndex + 20));
        }
  };

  const handleBoxClick = (box: any) => {
    setExpandedBox(box === expandedBox ? null : box);
  }
  
  return (
    <>
      <Head>
        <title>Igralishte - Product Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={product.title} />

        <div className="container-fluid my-5">
          <div className="row d-flex flex-column justify-content-center">
            <div className="col-11 mb-5">
                {/* renderiraj gi stavenite vo card to shop produkti */}
            </div>

            <div className="col-11">
                {/* kopcinjata za dodavanje/odzemanje quantity, presmetka i sumiranje vkupna suma  */}
            </div>

          {/* Box Component Item  */}
          {boxItemsData.map((boxItem, index) => {
            return (
              <BoxComponent key={index} boxItem={boxItem} onClick={() => handleBoxClick(boxItem)} expanded={boxItem === expandedBox}/>
            )
          })}

           {/* Other Related Product Items  */}
              <RelatedProducts key={currentIndex} products={randomProducts}/>

          <div className="d-flex flex-row">
            <div className="col-12 text-center mb-5" style={{letterSpacing: "3px"}}>
                {allProducts.length > 10 && (
                    <>
                    <button className="bg-transparent border-0 mr-3" onClick={handlePrevClick} disabled={page === 1}>
                        {'<'}
                    </button>
                    <span>{page} • {page + 1} • {page + 2} • {page + 3} • {page + 4} ... {totalPages}</span>
                    <button className="bg-transparent border-0 ml-3" onClick={handleNextClick} disabled={page === totalPages}>
                        {'>'}
                    </button>
                    </>
                )}
            </div>
          </div>
      </div>
    </div>
  </>
  );
};


export default OrderPage;




export const getStaticPaths: GetStaticPaths = async () => {

  const response = await fetch(`http://localhost:5001/products`); 
  const products: DataType["products"] = await response.json();


   const allProducts: ProductType[] = [];

      Object.values(products.vintageClothes).forEach((productList: ProductType[]) => {
          productList.forEach((product: ProductType) => {
              allProducts.push(product);
          });
      });


  const paths = allProducts?.map((product: ProductType) => ({
    params: {
      id: product.id,
    },
  }));

  
  return {
    paths,
    fallback: false,
  };
};



export const getStaticProps: GetStaticProps = async ({ params }) => {

  let product: ProductType | undefined = undefined;
  
  const resBoxItems = await fetch('http://localhost:5001/boxComponents'); 
  const boxItemsData = await resBoxItems.json();
  
  const response = await fetch(`http://localhost:5001/products`); 
  const products: DataType["products"] = await response.json();

  const allProducts: ProductType[] = [];

      Object.values(products.vintageClothes).forEach((productList: ProductType[]) => {
          productList.forEach((product: ProductType) => {
              allProducts.push(product);
          });
      });

  
 
const getRandomProducts = (products: ProductType[], quantity: number): ProductType[] => {
   const randomProducts: ProductType[] = [];

   for (let i = 0; i < quantity; i++) {
     const randomIndex = Math.floor(Math.random() * products.length);
     randomProducts.push(products[randomIndex]);

     // Za da nema duplikati
     products.splice(randomIndex, 1);
   }
   return randomProducts;
}

const randomProducts: ProductType[] = getRandomProducts(allProducts, 6);



  if (params?.id) {
    const resProduct = await fetch(`http://localhost:5001/products/${params.id}`);
    product = await resProduct.json();
  }


return {
    props: {
      product,
      allProducts,
      randomProducts,
      boxItemsData
    },
  };
};